project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute: 
  freeze: auto

website:
  title: "Julianna Renzi"
  repo-url: https://github.com/juliannajollyrenzi/juliannajollyrenzi.github.io/tree/main
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
    right: 
      - icon: github
        href: https://github.com/juliannajollyrenzi/juliannajollyrenzi.github.io/tree/main
  page-footer: 
    center: "Copyright 2025, Julianna Renzi"
    background: secondary

format:
  html:
    theme:
      light: theme_light.scss
      dark: theme_dark.scss
    mainfont: Special Gothic
    toc: true
    link-external-newwindow: true
    link-external-icon: false